### ISSUE TITLE
The way to actually use this

### ISSUE THREAD

**Issue by KonradLinkowski** [KonradLinkowski/MovieRatingAI#1]
There should be a file or command-line command to actually use this AI.
If you have any idea for a simple usage feel free to comment or create a PR

**Comment by pshkrh** [comment]
I believe you are doing this currently in main.py.

Maybe we can have something like `python main.py -i input_file.csv` and have it save the matplotlib plot in an output folder.

**Comment by pshkrh** [comment]
I can work on this, if you want. Forgot to mention

**Comment by KonradLinkowski** [comment]
@pshkrh I want a way to pass a movie data and get the score back, but your solution seems legit

**Comment by pshkrh** [comment]
@KonradLinkowski While trying to get the project to run on my end, I got an error from tensorflow about the history dictionary. The keys in `plot.py` `hist['mean_absolute_error'], hist['val_mean_absolute_error'], hist['mean_squared_error'], hist['val_mean_squared_error']` are causing a KeyError. Changing them to their shorthands `mae, val_mae` fixed the issue

I'm on tensorflow 2.3.1. If this is not intended, I'll raise a PR for this fix first, then I'll see about the command line issue, if that's okay.

**Comment by pshkrh** [comment]
@KonradLinkowski Thanks for merging the PR. When you mentioned you wanted the score as output, do you mean the flattened prediction array? If so, would you want that output in the console or would you want it in a text file?

**Comment by KonradLinkowski** [comment]
Yes. Output to the console is more convenient in terms of piping the scripts.
